apiVersion: v1
kind: ConfigMap
metadata:
  name: social-backend-config
  namespace: social-backend
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  JWT_ACCESS_EXPIRES: "15m"
  JWT_REFRESH_EXPIRES: "7d"
  KAFKA_CLIENT_ID: "social-backend"
  KAFKA_GROUP_ID: "social-backend-group"
  KAFKA_PARTITIONS: "3"
  KAFKA_REPLICATION: "3"
  # These reference internal K8s service DNS names
  KAFKA_BROKERS: "kafka-0.kafka-headless.social-backend.svc.cluster.local:9092,kafka-1.kafka-headless.social-backend.svc.cluster.local:9092,kafka-2.kafka-headless.social-backend.svc.cluster.local:9092"
  REDIS_URL: "redis://redis.social-backend.svc.cluster.local:6379"
