apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: social-backend

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis.yaml
  - kafka.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: social-backend
  app.kubernetes.io/managed-by: kustomize
